name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: Ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: .
          push: true
          tags: |
            cgomesv/somativa2:v1
            cgomesv/somativa2:latest
            
